version: '3'

services:
  testdatabase:
    image: mariadb:10.9
    container_name: testdatabase
    command:
      - mysqld
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    ports:
      - "3306:3306"
    environment:
      - MYSQL_DATABASE=database
      - MYSQL_ROOT_PASSWORD=password
    networks:
    - sql-migrate-git-network

networks:
  sql-migrate-git-network:
    external: true
