name: Build CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - "**"

jobs:
  build_ci:
    runs-on: ubuntu-latest
    env:
      IMAGE_NAME: docker-image
    steps:
      - name: Checkout with submodule
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          submodules: true

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Docker Build
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./build/Dockerfile
          push: false
          tags: sql-migrate-git
